import type { Metadata } from "next";
import { Poppins, Rock_Salt, Tektur } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "@/components/AppWalletProvider";

const poppins = Poppins({
  variable: "--font-popins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const rockSalt = Rock_Salt({
  variable: "--font-rockSalt",
  subsets: ["latin"],
  weight: ["400"],
});
const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${rockSalt.variable} ${tektur.variable}`}
      >
        <AppWalletProvider>{children}</AppWalletProvider>
      </body>
    </html>
  );
}
